import { TechnologyExperience } from "@/types/portfolio";

export const technologies: TechnologyExperience[] = [
  {
    id: "nextjs",
    name: "Next.js",
    category: "frontend",
    yearsOfExperience: 5,
    monthsOfExperience: 6,
    proficiency: "expert",
    firstUsed: "2019-09",
    lastUsed: "2025-03",
    relatedProjects: ["nucleus", "saudehd-platform", "investplus"],
    relatedDomains: ["frontend-engineering"],
    description: "Framework React para produção com SSR, SSG e otimizações avançadas.",
  },
  {
    id: "react",
    name: "React",
    category: "frontend",
    yearsOfExperience: 6,
    monthsOfExperience: 6,
    proficiency: "expert",
    firstUsed: "2018-09",
    lastUsed: "2025-03",
    relatedProjects: ["llamagov", "nucleus", "saudehd-platform", "investplus", "easyerp"],
    relatedDomains: ["frontend-engineering"],
    description: "Biblioteca JavaScript para construção de interfaces de usuário.",
  },
  {
    id: "angular",
    name: "Angular",
    category: "frontend",
    yearsOfExperience: 5,
    monthsOfExperience: 0,
    proficiency: "advanced",
    firstUsed: "2020-03",
    lastUsed: "2025-03",
    relatedProjects: ["mpro-assistencia-saude", "s4s-leadership", "investplus"],
    relatedDomains: ["frontend-engineering"],
    description: "Framework TypeScript para aplicações web escaláveis.",
  },
  {
    id: "typescript",
    name: "TypeScript",
    category: "frontend",
    yearsOfExperience: 7,
    monthsOfExperience: 0,
    proficiency: "expert",
    firstUsed: "2018-01",
    lastUsed: "2025-03",
    relatedProjects: ["llamagov", "nucleus", "saudehd-platform", "mpro-assistencia-saude", "investplus"],
    relatedDomains: ["frontend-engineering"],
    description: "Superset tipado do JavaScript para desenvolvimento escalável.",
  },
  {
    id: "react-native",
    name: "React Native",
    category: "mobile",
    yearsOfExperience: 5,
    monthsOfExperience: 3,
    proficiency: "advanced",
    firstUsed: "2019-12",
    lastUsed: "2025-03",
    relatedProjects: ["saudehd-platform", "hackathon-secitece"],
    relatedDomains: ["frontend-engineering"],
    description: "Framework para desenvolvimento de aplicativos móveis multiplataforma.",
  },
  {
    id: "nodejs",
    name: "Node.js",
    category: "backend",
    yearsOfExperience: 7,
    monthsOfExperience: 0,
    proficiency: "expert",
    firstUsed: "2018-01",
    lastUsed: "2025-03",
    relatedProjects: ["saudehd-platform", "investplus", "easyerp"],
    relatedDomains: ["backend-and-apis"],
    description: "Runtime JavaScript para desenvolvimento backend escalável.",
  },
  {
    id: "nestjs",
    name: "NestJS",
    category: "backend",
    yearsOfExperience: 5,
    monthsOfExperience: 6,
    proficiency: "expert",
    firstUsed: "2019-09",
    lastUsed: "2025-03",
    relatedProjects: ["saudehd-platform", "mpro-assistencia-saude", "s4s-leadership", "investplus"],
    relatedDomains: ["backend-and-apis"],
    description: "Framework Node.js progressivo para aplicações server-side eficientes.",
  },
  {
    id: "java",
    name: "Java",
    category: "backend",
    yearsOfExperience: 5,
    monthsOfExperience: 9,
    proficiency: "advanced",
    firstUsed: "2019-06",
    lastUsed: "2025-03",
    relatedProjects: ["mpro-assistencia-saude", "s4s-leadership"],
    relatedDomains: ["backend-and-apis"],
    description: "Linguagem de programação orientada a objetos para aplicações enterprise.",
  },
  {
    id: "spring",
    name: "Spring Framework",
    category: "backend",
    yearsOfExperience: 5,
    monthsOfExperience: 9,
    proficiency: "advanced",
    firstUsed: "2019-06",
    lastUsed: "2025-03",
    relatedProjects: ["mpro-assistencia-saude", "s4s-leadership", "investplus"],
    relatedDomains: ["backend-and-apis"],
    description: "Framework Java para desenvolvimento de aplicações enterprise.",
  },
  {
    id: "python",
    name: "Python",
    category: "ai",
    yearsOfExperience: 6,
    monthsOfExperience: 0,
    proficiency: "advanced",
    firstUsed: "2019-03",
    lastUsed: "2025-03",
    relatedProjects: ["llamagov", "saudehd-platform"],
    relatedDomains: ["ai-and-machine-learning"],
    description: "Linguagem de programação para desenvolvimento de soluções de IA e ML.",
  },
  {
    id: "tensorflow",
    name: "TensorFlow",
    category: "ai",
    yearsOfExperience: 5,
    monthsOfExperience: 0,
    proficiency: "intermediate",
    firstUsed: "2020-03",
    lastUsed: "2025-03",
    relatedProjects: ["saudehd-platform"],
    relatedDomains: ["ai-and-machine-learning"],
    description: "Framework de machine learning para desenvolvimento de modelos de IA.",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    category: "data",
    yearsOfExperience: 8,
    monthsOfExperience: 0,
    proficiency: "expert",
    firstUsed: "2017-01",
    lastUsed: "2025-03",
    relatedProjects: ["llamagov", "saudehd-platform", "mpro-assistencia-saude", "s4s-leadership", "investplus"],
    relatedDomains: ["backend-and-apis", "cloud-infrastructure"],
    description: "Sistema de gerenciamento de banco de dados relacional open-source.",
  },
  {
    id: "aws",
    name: "AWS",
    category: "infra",
    yearsOfExperience: 6,
    monthsOfExperience: 3,
    proficiency: "advanced",
    firstUsed: "2018-12",
    lastUsed: "2025-03",
    relatedProjects: ["saudehd-platform", "investplus"],
    relatedDomains: ["cloud-infrastructure"],
    description: "Plataforma de serviços em nuvem da Amazon para infraestrutura escalável.",
  },
  {
    id: "docker",
    name: "Docker",
    category: "infra",
    yearsOfExperience: 6,
    monthsOfExperience: 6,
    proficiency: "advanced",
    firstUsed: "2018-09",
    lastUsed: "2025-03",
    relatedProjects: ["llamagov", "mpro-assistencia-saude"],
    relatedDomains: ["cloud-infrastructure"],
    description: "Plataforma de containerização para desenvolvimento e deploy de aplicações.",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    category: "data",
    yearsOfExperience: 5,
    monthsOfExperience: 3,
    proficiency: "intermediate",
    firstUsed: "2019-12",
    lastUsed: "2025-03",
    relatedProjects: ["hackathon-secitece", "easyerp"],
    relatedDomains: ["backend-and-apis"],
    description: "Banco de dados NoSQL orientado a documentos.",
  },
  {
    id: "oracle",
    name: "Oracle",
    category: "data",
    yearsOfExperience: 5,
    monthsOfExperience: 6,
    proficiency: "intermediate",
    firstUsed: "2019-09",
    lastUsed: "2025-03",
    relatedProjects: ["mpro-assistencia-saude"],
    relatedDomains: ["cloud-infrastructure"],
    description: "Sistema de gerenciamento de banco de dados relacional enterprise.",
  },
  {
    id: "liquibase",
    name: "Liquibase",
    category: "infra",
    yearsOfExperience: 4,
    monthsOfExperience: 0,
    proficiency: "advanced",
    firstUsed: "2020-03",
    lastUsed: "2025-03",
    relatedProjects: ["mpro-assistencia-saude", "investplus"],
    relatedDomains: ["backend-and-apis"],
    description: "Ferramenta de versionamento e migração de banco de dados.",
  },
  {
    id: "maven",
    name: "Maven",
    category: "infra",
    yearsOfExperience: 5,
    monthsOfExperience: 9,
    proficiency: "advanced",
    firstUsed: "2019-06",
    lastUsed: "2025-03",
    relatedProjects: ["mpro-assistencia-saude"],
    relatedDomains: ["backend-and-apis"],
    description: "Ferramenta de gerenciamento de dependências e build para projetos Java.",
  },
  {
    id: "junit",
    name: "JUnit",
    category: "testing",
    yearsOfExperience: 5,
    monthsOfExperience: 9,
    proficiency: "advanced",
    firstUsed: "2019-06",
    lastUsed: "2025-03",
    relatedProjects: ["mpro-assistencia-saude"],
    relatedDomains: ["backend-and-apis"],
    description: "Framework de testes unitários para Java.",
  },
  {
    id: "mockito",
    name: "Mockito",
    category: "testing",
    yearsOfExperience: 5,
    monthsOfExperience: 9,
    proficiency: "advanced",
    firstUsed: "2019-06",
    lastUsed: "2025-03",
    relatedProjects: ["mpro-assistencia-saude"],
    relatedDomains: ["backend-and-apis"],
    description: "Framework de mocking para testes unitários em Java.",
  },
  {
    id: "scss",
    name: "SCSS",
    category: "frontend",
    yearsOfExperience: 5,
    monthsOfExperience: 0,
    proficiency: "advanced",
    firstUsed: "2020-03",
    lastUsed: "2025-03",
    relatedProjects: ["mpro-assistencia-saude"],
    relatedDomains: ["frontend-engineering"],
    description: "Pré-processador CSS com recursos avançados de estilização.",
  },
  {
    id: "karma",
    name: "Karma",
    category: "testing",
    yearsOfExperience: 5,
    monthsOfExperience: 0,
    proficiency: "advanced",
    firstUsed: "2020-03",
    lastUsed: "2025-03",
    relatedProjects: ["mpro-assistencia-saude"],
    relatedDomains: ["frontend-engineering"],
    description: "Test runner para testes unitários em JavaScript/TypeScript.",
  },
  {
    id: "jasmine",
    name: "Jasmine",
    category: "testing",
    yearsOfExperience: 5,
    monthsOfExperience: 0,
    proficiency: "advanced",
    firstUsed: "2020-03",
    lastUsed: "2025-03",
    relatedProjects: ["mpro-assistencia-saude"],
    relatedDomains: ["frontend-engineering"],
    description: "Framework de testes BDD para JavaScript.",
  },
  {
    id: "rancher",
    name: "Rancher",
    category: "infra",
    yearsOfExperience: 1,
    monthsOfExperience: 0,
    proficiency: "intermediate",
    firstUsed: "2024-12",
    lastUsed: "2025-03",
    relatedProjects: ["xvia-gov"],
    relatedDomains: ["cloud-infrastructure"],
    description: "Plataforma de gerenciamento de containers e Kubernetes.",
  },
  {
    id: "mariadb",
    name: "MariaDB",
    category: "data",
    yearsOfExperience: 1,
    monthsOfExperience: 0,
    proficiency: "intermediate",
    firstUsed: "2024-12",
    lastUsed: "2025-03",
    relatedProjects: ["xvia-gov"],
    relatedDomains: ["backend-and-apis"],
    description: "Sistema de gerenciamento de banco de dados relacional open-source.",
  },
  {
    id: "keycloak",
    name: "Keycloak",
    category: "infra",
    yearsOfExperience: 2,
    monthsOfExperience: 0,
    proficiency: "advanced",
    firstUsed: "2023-02",
    lastUsed: "2025-03",
    relatedProjects: ["xvia-gov", "s4s-tech-leadership"],
    relatedDomains: ["backend-and-apis", "cloud-infrastructure"],
    description: "Solução de gerenciamento de identidade e acesso (IAM) com SSO.",
  },
  {
    id: "webgate",
    name: "WebGate",
    category: "infra",
    yearsOfExperience: 1,
    monthsOfExperience: 0,
    proficiency: "intermediate",
    firstUsed: "2024-12",
    lastUsed: "2025-03",
    relatedProjects: ["xvia-gov"],
    relatedDomains: ["cloud-infrastructure"],
    description: "Gateway web para integração de sistemas governamentais.",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    category: "infra",
    yearsOfExperience: 2,
    monthsOfExperience: 0,
    proficiency: "intermediate",
    firstUsed: "2023-06",
    lastUsed: "2025-03",
    relatedProjects: ["xvia-gov", "llamagov"],
    relatedDomains: ["cloud-infrastructure"],
    description: "Plataforma de orquestração de containers para deploy e escalabilidade.",
  },
  {
    id: "cognito",
    name: "AWS Cognito",
    category: "infra",
    yearsOfExperience: 4,
    monthsOfExperience: 0,
    proficiency: "advanced",
    firstUsed: "2021-03",
    lastUsed: "2025-03",
    relatedProjects: ["saudehd-platform", "investplus"],
    relatedDomains: ["cloud-infrastructure"],
    description: "Serviço de gerenciamento de identidade e autenticação da AWS.",
  },
  {
    id: "route53",
    name: "AWS Route53",
    category: "infra",
    yearsOfExperience: 4,
    monthsOfExperience: 0,
    proficiency: "advanced",
    firstUsed: "2021-03",
    lastUsed: "2025-03",
    relatedProjects: ["saudehd-platform"],
    relatedDomains: ["cloud-infrastructure"],
    description: "Serviço de DNS gerenciado da AWS.",
  },
  {
    id: "wordpress",
    name: "WordPress",
    category: "frontend",
    yearsOfExperience: 3,
    monthsOfExperience: 0,
    proficiency: "intermediate",
    firstUsed: "2021-09",
    lastUsed: "2025-03",
    relatedProjects: ["saudehd-platform"],
    relatedDomains: ["frontend-engineering"],
    description: "Plataforma de gerenciamento de conteúdo para websites.",
  },
  {
    id: "ktor",
    name: "Ktor",
    category: "backend",
    yearsOfExperience: 1,
    monthsOfExperience: 6,
    proficiency: "intermediate",
    firstUsed: "2022-05",
    lastUsed: "2023-12",
    relatedProjects: ["vipps-internship"],
    relatedDomains: ["backend-and-apis"],
    description: "Framework assíncrono para Kotlin para desenvolvimento de aplicações web e APIs.",
  },
];

export function getTechnologyById(id: string): TechnologyExperience | undefined {
  return technologies.find((tech) => tech.id === id);
}

export function getTechnologiesByCategory(category: TechnologyExperience["category"]): TechnologyExperience[] {
  return technologies.filter((tech) => tech.category === category);
}

export function getTechnologiesByProject(projectId: string): TechnologyExperience[] {
  return technologies.filter((tech) => tech.relatedProjects.includes(projectId));
}

export function getTechnologiesByDomain(domainId: string): TechnologyExperience[] {
  return technologies.filter((tech) => tech.relatedDomains.includes(domainId));
}

export function getTotalExperienceMonths(tech: TechnologyExperience): number {
  return tech.yearsOfExperience * 12 + tech.monthsOfExperience;
}

export function formatExperience(tech: TechnologyExperience): string {
  const totalMonths = getTotalExperienceMonths(tech);
  const years = Math.floor(totalMonths / 12);
  const months = totalMonths % 12;
  
  if (years === 0) {
    return `${months} ${months === 1 ? "mês" : "meses"}`;
  }
  if (months === 0) {
    return `${years} ${years === 1 ? "ano" : "anos"}`;
  }
  return `${years} ${years === 1 ? "ano" : "anos"} e ${months} ${months === 1 ? "mês" : "meses"}`;
}

